// <auto-generated />
namespace PostIt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DeployCommit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeployCommit));
        
        string IMigrationMetadata.Id
        {
            get { return "202101241146487_DeployCommit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
